version: 0.2

env:
  variables:
    TF_VAR_project_name: "test-aws"
    TF_VAR_updated_from: "terraform"

phases:
  install:
    commands:
      - echo Entering install phase
      - apt-get update -y
      - apt-get install unzip -y
      - apt-get install curl -y
      - apt-get install wget -y
      - wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
      - unzip terraform*.zip
      - mv terraform /usr/local/bin
      - terraform -v
      - ls && pwd
  build:
    commands:
      - echo Entered buildphase
      - terraform init -backend-config=bucket=terraform-remote-state-5c1f261e-f412-4e1e-8907-63ba259ec6f5
      - terraform plan

  post_build:
    commands:
      - echo Entered postbuild phase
      - terraform apply -auto-approve
