steps:


  - name: 'gcr.io/herpaderp-1/terraform'
    args: ['init', '-backend-config=project=${PROJECT_ID}',
           '-backend-config=bucket=terraform-remote-state-5c1f261e-f412-4e1e-8907-63ba259ec6f5']
    env:
      - "TF_VAR_project-name=${PROJECT_ID}"
  - name: 'gcr.io/$PROJECT_ID/terraform'
    args: ['plan']
    env:
      - "TF_VAR_project-name=${PROJECT_ID}"


  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['apply', '-auto-approve']
    env:
      - "TF_VAR_project-name=${PROJECT_ID}"

    timeout: 500s
